package by.epam.safonenko.xml.type;

public enum  MedicineElement {
    MEDICAMENT,SUPPLEMENT, DOSAGE, FABRICATORS, FABRICATOR, CERTIFICATE,
    VERSIONS, VERSION, PACKS, PACK, TYPE, QUANTITY, PRICE, GROUP, ANALOG,
    ANALOGS, VITAMIN, VITAMINS, MEDICINES
}